services:
  #app:
  #  build: 
  #    dockerfile: Dockerfile
  #    context: .
  #  ports:
  #    - '8000:8000'
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://+:8000
  redis:
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=password
    volumes:
      - 'redis-data:/bitnami'
  db:
    image: 'bitnami/postgresql:latest'
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/bitnami'
      - './init/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh'
      - './init/basic.sql:/initialization/basic.sql'
      - './init/keycloak.dump:/initialization/keycloak.dump'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=booklibrary
      - POSTGRESQL_INITSCRIPTS_USERNAME=postgres
      - POSTGRESQL_INITSCRIPTS_PASSWORD=password
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
     - '8888:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=default@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_SERVER_MODE=False
    depends_on:
      - db
    volumes:
       - pgadmin-data:/var/lib/pgadmin
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - HTTP_USER=default
      - HTTP_PASSWORD=password
    ports:
      - 8081:8081
    depends_on:
      - redis
  keycloak:
    image: bitnami/keycloak:latest
    restart: unless-stopped
    ports:
     - '8080:8080'
    environment:
      - 'KEYCLOAK_ADMIN=default'
      - 'KEYCLOAK_ADMIN_PASSWORD=password'
      - 'KEYCLOAK_DATABASE_VENDOR=postgresql'
      - 'KEYCLOAK_DATABASE_HOST=db'
      - 'KEYCLOAK_DATABASE_PORT=5432'
      - 'KEYCLOAK_DATABASE_USER=keycloak'
      - 'KEYCLOAK_DATABASE_NAME=keycloak'
      - 'KEYCLOAK_DATABASE_PASSWORD=password'
      - 'KEYCLOAK_DATABASE_SCHEMA=public'
      - 'KEYCLOAK_PRODUCTION=false'
      - 'KEYCLOAK_ENABLE_HTTPS=false'
    depends_on:
      - db

volumes:
  redis-data:
  db-data:
  pgadmin-data: